import { createServerFn } from "@tanstack/react-start";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Public endpoint: returns ONLY the cached AI summary.
 * Never triggers a paid AI call from anonymous traffic — protects
 * LOVABLE_API_KEY budget from cost-abuse via the public game pages.
 * Summaries are generated by authenticated admins via
 * `generateGameReviewsSummary` below.
 */
export const getGameReviewsSummary = createServerFn({ method: "POST" })
  .inputValidator((d: { id: string }) => {
    if (!d?.id || typeof d.id !== "string" || !UUID_RE.test(d.id)) {
      throw new Error("id inválido");
    }
    return d;
  })
  .handler(async ({ data }) => {
    const { data: game, error } = await supabaseAdmin
      .from("games")
      .select("id,reviews_summary,reviews_summary_updated_at")
      .eq("id", data.id)
      .eq("published", true)
      .maybeSingle();
    if (error) throw new Error(error.message);
    if (!game) throw new Error("Jogo não encontrado");

    if (game.reviews_summary) {
      return { summary: game.reviews_summary as string, cached: true, available: true };
    }
    return { summary: null, cached: false, available: false };
  });

/**
 * Authenticated endpoint: generates (or refreshes) the AI summary for a game.
 * Restricted to logged-in users to prevent anonymous cost-abuse of the
 * Lovable AI gateway.
 */
export const generateGameReviewsSummary = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: { id: string; force?: boolean }) => {
    if (!d?.id || typeof d.id !== "string" || !UUID_RE.test(d.id)) {
      throw new Error("id inválido");
    }
    return d;
  })
  .handler(async ({ data, context }) => {
    const { data: game, error } = await supabaseAdmin
      .from("games")
      .select("id,title,developer,platform,reviews_summary,reviews_summary_updated_at")
      .eq("id", data.id)
      .eq("published", true)
      .maybeSingle();
    if (error) throw new Error(error.message);
    if (!game) throw new Error("Jogo não encontrado");

    // Only admins may bypass the 30-day cache via `force: true`.
    let force = false;
    if (data.force) {
      const { data: roles } = await supabaseAdmin
        .from("user_roles")
        .select("role")
        .eq("user_id", context.userId);
      force = roles?.some((r) => r.role === "admin") ?? false;
    }

    const cachedAt = game.reviews_summary_updated_at ? new Date(game.reviews_summary_updated_at).getTime() : 0;
    const fresh = Date.now() - cachedAt < 1000 * 60 * 60 * 24 * 30;
    if (!force && game.reviews_summary && fresh) {
      return { summary: game.reviews_summary as string, cached: true };
    }

    const apiKey = process.env.LOVABLE_API_KEY;
    if (!apiKey) throw new Error("LOVABLE_API_KEY ausente");

    const prompt = `Você é um curador gamer. Resuma em português brasileiro a recepção dos jogadores ao jogo "${game.title}" (desenvolvedora: ${game.developer ?? "?"}, plataforma: ${game.platform}). 
Estruture em 4 seções curtas com títulos em **negrito** markdown:
1. **Visão geral** — 1 parágrafo (3-4 frases) sobre o tom geral das reviews.
2. **O que jogadores elogiam** — 3 a 5 bullets.
3. **Críticas recorrentes** — 2 a 4 bullets.
4. **Para quem é** — 1 frase de recomendação.
Seja honesto, conciso e baseado no consenso público das reviews. Não invente notas numéricas específicas.`;

    const resp = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [{ role: "user", content: prompt }],
      }),
    });
    if (!resp.ok) {
      const txt = await resp.text();
      throw new Error(`AI gateway: ${resp.status} ${txt.slice(0, 200)}`);
    }
    const json: any = await resp.json();
    const summary: string = json?.choices?.[0]?.message?.content ?? "";
    if (!summary) throw new Error("Resposta vazia do modelo");

    await supabaseAdmin
      .from("games")
      .update({ reviews_summary: summary, reviews_summary_updated_at: new Date().toISOString() })
      .eq("id", game.id);

    return { summary, cached: false };
  });
