/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SteamRouteImport } from './routes/steam'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OutrosRouteImport } from './routes/outros'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuiasRouteImport } from './routes/guias'
import { Route as EpicRouteImport } from './routes/epic'
import { Route as CulturaRouteImport } from './routes/cultura'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JogosIdRouteImport } from './routes/jogos.$id'
import { Route as GuiasIdRouteImport } from './routes/guias.$id'
import { Route as CulturaSlugRouteImport } from './routes/cultura.$slug'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as ApiPublicSyncGamesRouteImport } from './routes/api/public/sync-games'
import { Route as AdminAdminTicketsRouteImport } from './routes/_admin/admin.tickets'
import { Route as AdminAdminSyncRouteImport } from './routes/_admin/admin.sync'
import { Route as AdminAdminSubscribersRouteImport } from './routes/_admin/admin.subscribers'
import { Route as AdminAdminGuidesRouteImport } from './routes/_admin/admin.guides'
import { Route as AdminAdminGamesRouteImport } from './routes/_admin/admin.games'
import { Route as AdminAdminFaqRouteImport } from './routes/_admin/admin.faq'
import { Route as AdminAdminCultureRouteImport } from './routes/_admin/admin.culture'

const SteamRoute = SteamRouteImport.update({
  id: '/steam',
  path: '/steam',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OutrosRoute = OutrosRouteImport.update({
  id: '/outros',
  path: '/outros',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasRoute = GuiasRouteImport.update({
  id: '/guias',
  path: '/guias',
  getParentRoute: () => rootRouteImport,
} as any)
const EpicRoute = EpicRouteImport.update({
  id: '/epic',
  path: '/epic',
  getParentRoute: () => rootRouteImport,
} as any)
const CulturaRoute = CulturaRouteImport.update({
  id: '/cultura',
  path: '/cultura',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosIdRoute = JogosIdRouteImport.update({
  id: '/jogos/$id',
  path: '/jogos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasIdRoute = GuiasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GuiasRoute,
} as any)
const CulturaSlugRoute = CulturaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CulturaRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicSyncGamesRoute = ApiPublicSyncGamesRouteImport.update({
  id: '/api/public/sync-games',
  path: '/api/public/sync-games',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminTicketsRoute = AdminAdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSyncRoute = AdminAdminSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSubscribersRoute = AdminAdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminGuidesRoute = AdminAdminGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminGamesRoute = AdminAdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminFaqRoute = AdminAdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCultureRoute = AdminAdminCultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cultura': typeof CulturaRouteWithChildren
  '/epic': typeof EpicRoute
  '/guias': typeof GuiasRouteWithChildren
  '/login': typeof LoginRoute
  '/outros': typeof OutrosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/steam': typeof SteamRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/cultura/$slug': typeof CulturaSlugRoute
  '/guias/$id': typeof GuiasIdRoute
  '/jogos/$id': typeof JogosIdRoute
  '/admin/culture': typeof AdminAdminCultureRoute
  '/admin/faq': typeof AdminAdminFaqRoute
  '/admin/games': typeof AdminAdminGamesRoute
  '/admin/guides': typeof AdminAdminGuidesRoute
  '/admin/subscribers': typeof AdminAdminSubscribersRoute
  '/admin/sync': typeof AdminAdminSyncRoute
  '/admin/tickets': typeof AdminAdminTicketsRoute
  '/api/public/sync-games': typeof ApiPublicSyncGamesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cultura': typeof CulturaRouteWithChildren
  '/epic': typeof EpicRoute
  '/guias': typeof GuiasRouteWithChildren
  '/login': typeof LoginRoute
  '/outros': typeof OutrosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/steam': typeof SteamRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/cultura/$slug': typeof CulturaSlugRoute
  '/guias/$id': typeof GuiasIdRoute
  '/jogos/$id': typeof JogosIdRoute
  '/admin/culture': typeof AdminAdminCultureRoute
  '/admin/faq': typeof AdminAdminFaqRoute
  '/admin/games': typeof AdminAdminGamesRoute
  '/admin/guides': typeof AdminAdminGuidesRoute
  '/admin/subscribers': typeof AdminAdminSubscribersRoute
  '/admin/sync': typeof AdminAdminSyncRoute
  '/admin/tickets': typeof AdminAdminTicketsRoute
  '/api/public/sync-games': typeof ApiPublicSyncGamesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/cultura': typeof CulturaRouteWithChildren
  '/epic': typeof EpicRoute
  '/guias': typeof GuiasRouteWithChildren
  '/login': typeof LoginRoute
  '/outros': typeof OutrosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/steam': typeof SteamRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/cultura/$slug': typeof CulturaSlugRoute
  '/guias/$id': typeof GuiasIdRoute
  '/jogos/$id': typeof JogosIdRoute
  '/_admin/admin/culture': typeof AdminAdminCultureRoute
  '/_admin/admin/faq': typeof AdminAdminFaqRoute
  '/_admin/admin/games': typeof AdminAdminGamesRoute
  '/_admin/admin/guides': typeof AdminAdminGuidesRoute
  '/_admin/admin/subscribers': typeof AdminAdminSubscribersRoute
  '/_admin/admin/sync': typeof AdminAdminSyncRoute
  '/_admin/admin/tickets': typeof AdminAdminTicketsRoute
  '/api/public/sync-games': typeof ApiPublicSyncGamesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cultura'
    | '/epic'
    | '/guias'
    | '/login'
    | '/outros'
    | '/sitemap.xml'
    | '/sobre'
    | '/steam'
    | '/admin'
    | '/cultura/$slug'
    | '/guias/$id'
    | '/jogos/$id'
    | '/admin/culture'
    | '/admin/faq'
    | '/admin/games'
    | '/admin/guides'
    | '/admin/subscribers'
    | '/admin/sync'
    | '/admin/tickets'
    | '/api/public/sync-games'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cultura'
    | '/epic'
    | '/guias'
    | '/login'
    | '/outros'
    | '/sitemap.xml'
    | '/sobre'
    | '/steam'
    | '/admin'
    | '/cultura/$slug'
    | '/guias/$id'
    | '/jogos/$id'
    | '/admin/culture'
    | '/admin/faq'
    | '/admin/games'
    | '/admin/guides'
    | '/admin/subscribers'
    | '/admin/sync'
    | '/admin/tickets'
    | '/api/public/sync-games'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/cultura'
    | '/epic'
    | '/guias'
    | '/login'
    | '/outros'
    | '/sitemap.xml'
    | '/sobre'
    | '/steam'
    | '/_admin/admin'
    | '/cultura/$slug'
    | '/guias/$id'
    | '/jogos/$id'
    | '/_admin/admin/culture'
    | '/_admin/admin/faq'
    | '/_admin/admin/games'
    | '/_admin/admin/guides'
    | '/_admin/admin/subscribers'
    | '/_admin/admin/sync'
    | '/_admin/admin/tickets'
    | '/api/public/sync-games'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CulturaRoute: typeof CulturaRouteWithChildren
  EpicRoute: typeof EpicRoute
  GuiasRoute: typeof GuiasRouteWithChildren
  LoginRoute: typeof LoginRoute
  OutrosRoute: typeof OutrosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  SteamRoute: typeof SteamRoute
  JogosIdRoute: typeof JogosIdRoute
  ApiPublicSyncGamesRoute: typeof ApiPublicSyncGamesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/steam': {
      id: '/steam'
      path: '/steam'
      fullPath: '/steam'
      preLoaderRoute: typeof SteamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outros': {
      id: '/outros'
      path: '/outros'
      fullPath: '/outros'
      preLoaderRoute: typeof OutrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias': {
      id: '/guias'
      path: '/guias'
      fullPath: '/guias'
      preLoaderRoute: typeof GuiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epic': {
      id: '/epic'
      path: '/epic'
      fullPath: '/epic'
      preLoaderRoute: typeof EpicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultura': {
      id: '/cultura'
      path: '/cultura'
      fullPath: '/cultura'
      preLoaderRoute: typeof CulturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/$id': {
      id: '/jogos/$id'
      path: '/jogos/$id'
      fullPath: '/jogos/$id'
      preLoaderRoute: typeof JogosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/$id': {
      id: '/guias/$id'
      path: '/$id'
      fullPath: '/guias/$id'
      preLoaderRoute: typeof GuiasIdRouteImport
      parentRoute: typeof GuiasRoute
    }
    '/cultura/$slug': {
      id: '/cultura/$slug'
      path: '/$slug'
      fullPath: '/cultura/$slug'
      preLoaderRoute: typeof CulturaSlugRouteImport
      parentRoute: typeof CulturaRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/sync-games': {
      id: '/api/public/sync-games'
      path: '/api/public/sync-games'
      fullPath: '/api/public/sync-games'
      preLoaderRoute: typeof ApiPublicSyncGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/tickets': {
      id: '/_admin/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminAdminTicketsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/sync': {
      id: '/_admin/admin/sync'
      path: '/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AdminAdminSyncRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/subscribers': {
      id: '/_admin/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminAdminSubscribersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/guides': {
      id: '/_admin/admin/guides'
      path: '/guides'
      fullPath: '/admin/guides'
      preLoaderRoute: typeof AdminAdminGuidesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/games': {
      id: '/_admin/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminAdminGamesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/faq': {
      id: '/_admin/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminAdminFaqRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/culture': {
      id: '/_admin/admin/culture'
      path: '/culture'
      fullPath: '/admin/culture'
      preLoaderRoute: typeof AdminAdminCultureRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminCultureRoute: typeof AdminAdminCultureRoute
  AdminAdminFaqRoute: typeof AdminAdminFaqRoute
  AdminAdminGamesRoute: typeof AdminAdminGamesRoute
  AdminAdminGuidesRoute: typeof AdminAdminGuidesRoute
  AdminAdminSubscribersRoute: typeof AdminAdminSubscribersRoute
  AdminAdminSyncRoute: typeof AdminAdminSyncRoute
  AdminAdminTicketsRoute: typeof AdminAdminTicketsRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminCultureRoute: AdminAdminCultureRoute,
  AdminAdminFaqRoute: AdminAdminFaqRoute,
  AdminAdminGamesRoute: AdminAdminGamesRoute,
  AdminAdminGuidesRoute: AdminAdminGuidesRoute,
  AdminAdminSubscribersRoute: AdminAdminSubscribersRoute,
  AdminAdminSyncRoute: AdminAdminSyncRoute,
  AdminAdminTicketsRoute: AdminAdminTicketsRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CulturaRouteChildren {
  CulturaSlugRoute: typeof CulturaSlugRoute
}

const CulturaRouteChildren: CulturaRouteChildren = {
  CulturaSlugRoute: CulturaSlugRoute,
}

const CulturaRouteWithChildren =
  CulturaRoute._addFileChildren(CulturaRouteChildren)

interface GuiasRouteChildren {
  GuiasIdRoute: typeof GuiasIdRoute
}

const GuiasRouteChildren: GuiasRouteChildren = {
  GuiasIdRoute: GuiasIdRoute,
}

const GuiasRouteWithChildren = GuiasRoute._addFileChildren(GuiasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CulturaRoute: CulturaRouteWithChildren,
  EpicRoute: EpicRoute,
  GuiasRoute: GuiasRouteWithChildren,
  LoginRoute: LoginRoute,
  OutrosRoute: OutrosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  SteamRoute: SteamRoute,
  JogosIdRoute: JogosIdRoute,
  ApiPublicSyncGamesRoute: ApiPublicSyncGamesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
